ARG PLAYWRIGHT_VERSION=1.61.1
FROM node:26-bookworm

ARG PLAYWRIGHT_VERSION
RUN npx -y playwright@${PLAYWRIGHT_VERSION} install --with-deps chromium && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /work
